import Head from "next/head";
import App from "components/app";
import AppProvider from "components/context";

export default function Home({ apiKey, firebaseAPI, firebaseDatabaseURL }) {
  return (
    <>
      <Head>
        <title>Accident Blackspots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppProvider>
          <App
            apiKey={apiKey}
            firebaseAPI={firebaseAPI}
            firebaseDatabaseURL={firebaseDatabaseURL}
          />
        </AppProvider>
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      apiKey: process.env.MAPBOX_API_KEY,
      firebaseAPI: process.env.FIREBASE_API_KEY,
      firebaseDatabaseURL: process.env.FIREBASE_DATABASE_URL,
    },
  };
}
