import Head from "next/head";
import App from "components/app";
import AppProvider from "components/context";
import React from "react";
export default function Home({ apiKey }) {
  return (
    <>
      <Head>
        <title>Accident Blackspots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppProvider>
          <App apiKey={apiKey} />
        </AppProvider>
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      apiKey: process.env.MAPBOX_API_KEY,
    },
  };
}
